apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: iticket-ingress
  namespace: iticket-dev
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          # 1) Backend health endpoint
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 5000

          # 2) Backend API endpoints
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 5000

          # 3) Everything else goes to frontend
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
